### PR TITLE
Experimental CK2 minRMSD-based clustering

### PR DESCRIPTION
**Pull request by jchodera**
This PR checks in a script to do a very basic minRMSD-based clustering of CK2 with equitemporal generator selection.

Clustered snapshot identities are on `hal` here:
```
/cbio/jclab/home/chodera/github/choderalab/msms/MSMs.jchodera/jchodera/CK2/pyemma
```

### CODE REVIEW

**Comment by rafwiewiora** [comment]
So do you still think there's something wrong with the clustering in PyEMMA? You mentioned you were getting weird results on this dataset too? I would love to do something proved to work ok on the SETD8 dataset.

**Comment by jchodera** [comment]
I suspect there is.  I think we should test on something simple like the alanine dipeptide dataset from MSMBuilder.

**Comment by rafwiewiora** [comment]
ok!

**Comment by jchodera** [comment]
@rafwiewiora: Are you or @maxentile able to take a stab at testing minRMSD clustering on an alanine dipeptide dataset, or should I do that?

**Comment by maxentile** [comment]
Hi, what exactly are we interested in testing here? Regular-time clustering will probably be fragile, regardless of metric...

**Comment by maxentile** [comment]
To do the same analysis except with the alanine dipeptide dataset in `msmbuilder`, we can insert:
```python
from msmbuilder.example_datasets import AlanineDipeptide
trajs = AlanineDipeptide().get().trajectories
trajectory_filenames = []
for i,traj in enumerate(trajs):
    fname = 'alanine_{0}.h5'.format(i)
    trajectory_filenames.append(fname)
    traj.save_hdf5(fname)
```
before line 36 in `cluster.py`.

Are we interested in checking for correctness of the `pyemma` implementation? Or some measure of the quality of the resulting discretization?

**Comment by maxentile** [comment]
When looking at coarse-graining algorithms a few months ago, I had collected some results on this dataset with a different clustering algorithm (k-medoids), but the same metric (minRMSD) -- in case this of interest here: https://github.com/maxentile/automatic-state-decomposition/blob/master/decompose-py/Alanine%20benchmark%20%2B%20performance%20comparison.ipynb

**Comment by jchodera** [comment]
Thanks, @maxentile!  To be clearer here: The resulting timescales from my minRMSD clustering of 1M CK2 datapoints was so poor that it was highly reminiscent of earlier bugs in my own minRMSD code when the bugs caused the code to produce incorrect Voronoi partitions of configuration space.  I wanted to be sure of the following things:
* the code produces the same results with 1 thread or N > 1 threads for equitemporal spacing
* the code produces a Voronoi partitioning of space, with each configuration assigned to the closest generator and the generators selected equitemporally

That code snippet will very much help!

**Comment by jchodera** [comment]
That notebook with K-medoids minRMSD clustering gives a *beautiful* implied timescales plot, by the way.

**Comment by jchodera** [comment]
I'm going to check this in now because I finally have *something* that works and the scripts may be useful to others.

**Pull request merged**
